# Generated by Django 5.0.1 on 2025-11-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="supabase_id",
            field=models.CharField(
                blank=True,
                help_text="Supabase Auth user UUID",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
