# Generated by Django 5.0.1 on 2025-11-25 12:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AadhaarDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_file", models.ImageField(upload_to="raw/%Y/%m/%d/")),
                (
                    "preprocessed_file",
                    models.ImageField(
                        blank=True, null=True, upload_to="processed/%Y/%m/%d/"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="thumbnails/%Y/%m/%d/"
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.IntegerField(help_text="File size in bytes")),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Group ID for batch processing",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "batch_position",
                    models.IntegerField(
                        blank=True, help_text="Position in batch", null=True
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="documents_a_status_b9b43d_idx"
                    ),
                    models.Index(
                        fields=["batch_id"], name="documents_a_batch_i_c2370a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_text",
                    models.TextField(
                        blank=True, help_text="Full OCR text extracted from document"
                    ),
                ),
                (
                    "aadhaar_number",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "date_of_birth",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("gender", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "gemini_response",
                    models.TextField(blank=True, help_text="Full Gemini API response"),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        blank=True,
                        help_text="Overall confidence score (0-1)",
                        null=True,
                    ),
                ),
                ("is_authentic", models.BooleanField(blank=True, null=True)),
                (
                    "fraud_indicators",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of detected fraud indicators",
                    ),
                ),
                (
                    "quality_issues",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Image quality issues detected",
                    ),
                ),
                (
                    "extracted_fields",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional fields extracted from document",
                    ),
                ),
                ("analyzed_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="documents.aadhaardocument",
                    ),
                ),
            ],
        ),
    ]
