# Generated by Django 5.0.1 on 2025-11-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentmetadata",
            name="fraud_detection",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="YOLO and CV-based fraud detection results",
            ),
        ),
    ]
