# Generated by Django 5.0.1 on 2025-11-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_aadhaardocument_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="aadhaardocument",
            name="storage_type",
            field=models.CharField(
                choices=[("local", "Local Storage"), ("supabase", "Supabase Storage")],
                default="local",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="aadhaardocument",
            name="supabase_original_path",
            field=models.CharField(
                blank=True,
                help_text="Path in Supabase Storage for original file",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="aadhaardocument",
            name="supabase_processed_path",
            field=models.CharField(
                blank=True,
                help_text="Path in Supabase Storage for processed file",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="aadhaardocument",
            name="supabase_thumbnail_path",
            field=models.CharField(
                blank=True,
                help_text="Path in Supabase Storage for thumbnail",
                max_length=500,
                null=True,
            ),
        ),
    ]
