# Generated by Django 5.0.1 on 2025-12-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_aadhaardocument_storage_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhaardocument',
            name='batch_id',
            field=models.CharField(blank=True, db_index=True, help_text='Group ID for batch processing', max_length=255, null=True),
        ),
    ]
