# Generated by Django 5.0.1 on 2025-12-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_aadhaardocument_batch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhaardocument',
            name='original_file',
            field=models.ImageField(max_length=500, upload_to='raw/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='aadhaardocument',
            name='preprocessed_file',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='processed/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='aadhaardocument',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='thumbnails/%Y/%m/%d/'),
        ),
    ]
